### ISSUE TITLE
pod port hostIP option not properly handled when creating iptables chain

### ISSUE THREAD

**Issue by mgcrea** [flannel-io/flannel#1019]
Following [this kubernetes issue](https://github.com/kubernetes/kubernetes/issues/65976), it looks like I'm encountering an iptables-related bug when I'm using using a proxy-pod to forward both `80/http` and `443/https` privileged ports to an `ingress-nginx` service using the following configuration:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ingress-proxy
  namespace: ingress-nginx
spec:
  containers:
  - name: proxy-http
    image: gcr.io/google_containers/proxy-to-service:v2
    args: [ "tcp", "80", "ingress-nginx.ingress-nginx" ]
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
      hostPort: 80
      hostIP: 37.59.4.29
  - name: proxy-https
    image: gcr.io/google_containers/proxy-to-service:v2
    args: [ "tcp", "443", "ingress-nginx.ingress-nginx" ]
    ports:
    - name: https
      protocol: TCP
      containerPort: 443
      hostPort: 443
      hostIP: 37.59.4.29
```

Unfortunately, the iptables rules created are not properly bound to the hostIp, and starts highjacking trafic on every other IP on the server (breaking existing services on other IPs):

## Expected Behavior

Should produce a good iptables chain, scoped on the given `$hostIp`

```
# iptables -n -t nat -L CNI-DN-25b3bc1bba035c69d2969
Chain CNI-DN-25b3bc1bba035c69d2969 (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            37.59.4.29           tcp dpt:80 to:10.244.0.89:80
DNAT       tcp  --  0.0.0.0/0            37.59.4.29           tcp dpt:443 to:10.244.0.89:443
```

## Current Behavior

Produces a bad iptables chain on listening on `0.0.0.0/0

```
# iptables -n -t nat -L CNI-DN-25b3bc1bba035c69d2969
Chain CNI-DN-25b3bc1bba035c69d2969 (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:80 to:10.244.0.89:80
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:443 to:10.244.0.89:443
```

## Possible Solution

Temp fix:

```
iptables -t nat -R CNI-DN-25b3bc1bba035c69d2969 1 -p tcp -d 37.59.4.29 --dport 80 -j DNAT --to-destination 10.244.0.89:80
iptables -t nat -R CNI-DN-25b3bc1bba035c69d2969 2 -p tcp -d 37.59.4.29 --dport 443 -j DNAT --to-destination 10.244.0.89:443
```

## Steps to Reproduce (for bugs)

1. Use above pod yaml
2. Check iptables chains

## Your Environment

- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
Bare metal setup via kubeadm
```
- OS (e.g. from /etc/os-release):
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux fr-3eaa 4.15.0-23-generic #25~16.04.1-Ubuntu SMP Fri May 25 04:50:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:

> Using flannel (followed official kubeadm tutorial):
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
```
> Up-to-date (non-supported) docker:
```
# docker -v
Docker version 18.03.1-ce, build 9ee9f40
```
