### ISSUE TITLE
helm

### ISSUE THREAD

**Issue by mosaicwang** [flannel-io/flannel#1093]
## Expected Behavior

can execute `helm list` without error

## Current Behavior

execute `helm list` return `Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: connect: no route to host`

## Steps to Reproduce (for bugs)

1.create serviceaccount and clusterrolebinding :
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller    
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller    
    namespace: kube-system
```    
2. init tiller
```
helm init --service-account tiller \
	-i registry.aliyuncs.com/google_containers/tiller:${helm_ver} \
	--stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
```
3.`kubectl get pods -n kube-system`
```
NAME                                   READY   STATUS    RESTARTS   AGE
coredns-78d4cf999f-c6rh6               1/1     Running   0          128m
coredns-78d4cf999f-mxx9h               1/1     Running   0          128m
etcd-mymaster                          1/1     Running   0          133m
kube-apiserver-mymaster                1/1     Running   0          132m
kube-controller-manager-mymaster       1/1     Running   1          133m
kube-flannel-ds-amd64-99lnc            1/1     Running   0          40m
kube-flannel-ds-amd64-9t9m8            1/1     Running   0          41m
kube-proxy-4qrsw                       1/1     Running   0          133m
kube-proxy-j8ws5                       1/1     Running   0          40m
kube-scheduler-mymaster                1/1     Running   1          132m
kubernetes-dashboard-f94567dff-2cfhf   1/1     Running   0          108m
tiller-deploy-6599cfbbb9-rn9kz         1/1     Running   0          39m

```
4.check helm and tiller
`helm version`
```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```
`helm list`
```
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: connect: no route to host
```

## Your Environment

* Flannel version:0.10.0 and 0.11.0 both error
* Backend used (e.g. vxlan or udp):vxlan
* Etcd version:
* Kubernetes version (if used):1.13.2
* Operating System and version:Centos 7.6 1810
* helm and tiller version: 2.12.2
* Link to your project (optional):
