### ISSUE TITLE
after apply flannel, kubelet reports error

### ISSUE THREAD

**Issue by wonleing** [flannel-io/flannel#1288]
## Expected Behavior
after apply flannel.yaml, kubelet report no errors.

## Current Behavior
after apply flannel.yaml, kubelet reports following error:

16:47:21 uos-pc kubelet[8631]: E0426 16:47:21.310812    8631 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to set up sandbox container "e7f634f38543fd81ff951da60ece6eb997cec653f6992e50647abb153cbf4fe0" network for pod "coredns-859fd9b8b5-lv6hf": NetworkPlugin cni failed to set up pod "coredns-859fd9b8b5-lv6hf_kube-system" network: Failed to open current namespace: failed to Statfs "/proc/25085/task/1439572/ns/net": no such file or directory
16:47:21 uos-pc kubelet[8631]: E0426 16:47:21.311073    8631 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "coredns-859fd9b8b5-lv6hf_kube-system(a26088cb-8798-11ea-90c7-00e000e0a30c)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "e7f634f38543fd81ff951da60ece6eb997cec653f6992e50647abb153cbf4fe0" network for pod "coredns-859fd9b8b5-lv6hf": NetworkPlugin cni failed to set up pod "coredns-859fd9b8b5-lv6hf_kube-system" network: Failed to open current namespace: failed to Statfs "/proc/25085/task/1439572/ns/net": no such file or directory
4- 26 16:47:21 uos-pc kubelet[8631]: E0426 16:47:21.311149    8631 kuberuntime_manager.go:662] createPodSandbox for pod "coredns-859fd9b8b5-lv6hf_kube-system(a26088cb-8798-11ea-90c7-00e000e0a30c)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "e7f634f38543fd81ff951da60ece6eb997cec653f6992e50647abb153cbf4fe0" network for pod "coredns-859fd9b8b5-lv6hf": NetworkPlugin cni failed to set up pod "coredns-859fd9b8b5-lv6hf_kube-system" network: Failed to open current namespace: failed to Statfs "/proc/25085/task/1439572/ns/net": no such file or directory
16:47:21 uos-pc kubelet[8631]: E0426 16:47:21.311504    8631 pod_workers.go:190] Error syncing pod a26088cb-8798-11ea-90c7-00e000e0a30c ("coredns-859fd9b8b5-lv6hf_kube-system(a26088cb-8798-11ea-90c7-00e000e0a30c)"), skipping: failed to "CreatePodSandbox" for "coredns-859fd9b8b5-lv6hf_kube-system(a26088cb-8798-11ea-90c7-00e000e0a30c)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-859fd9b8b5-lv6hf_kube-system(a26088cb-8798-11ea-90c7-00e000e0a30c)\" failed: rpc error: code = Unknown desc = failed to set up sandbox container \"e7f634f38543fd81ff951da60ece6eb997cec653f6992e50647abb153cbf4fe0\" network for pod \"coredns-859fd9b8b5-lv6hf\": NetworkPlugin cni failed to set up pod \"coredns-859fd9b8b5-lv6hf_kube-system\" network: Failed to open current namespace: failed to Statfs \"/proc/25085/task/1439572/ns/net\": no such file or directory"
16:47:22 uos-pc kubelet[8631]: E0426 16:47:22.020161    8631 cni.go:324] Error adding kube-system_coredns-859fd9b8b5-66z8l/04bac93236ca6e580a8b89e8bb1c098fadfe12b6b5bf19d2ce7326e33f8ebeda to network loopback/cni-loopback: Failed to open current namespace: failed to Statfs "/proc/25236/task/1439572/ns/net": no such file or directory

## Possible Solution
change flannel.yaml content?

## Steps to Reproduce (for bugs)
kubectl apply -f flannel.yaml
systemctl status kubectl 

## Your Environment

* Flannel version: 0.8.5
flannel.yaml:
```

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
erbs:
      - patch
---
kind: ClusterRoleBinding
piVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]

  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-sw64
  namespace: kube-system
  labels:
    tier: node
    app: flannel

  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: sw64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      initContainers:
      - name: install-cni
        image: harbor.sh.deepin.com/nonfree/flannel:uos
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conflist; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      containers:
      - name: kube-flannel
        image: <a self built flannel image, using this project>
        imagePullPolicy: Never
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg
---

```
