### ISSUE TITLE
k8s 1.19.0 with kube-flannel 0.12 Error registering network: failed to acquire lease: node "nodeName" pod cidr not assigned

### ISSUE THREAD

**Issue by thanos1983** [flannel-io/flannel#1344]
## Expected Behavior

Launching the Master node

## Current Behavior

The master node can not start

## Steps to Reproduce (for bugs)

1. Launch the prime master node with version 1.19.0 on bare metal and using the latest stable flannel version
2. Since the node will not start check the logs to see the error

## Context

I am trying to use flannel as a main network pod.

## Your Environment

* Flannel version: v0.12.0-amd64
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 
* Kubernetes version (if used): v1.19.0
* Operating System and version: Red Hat Enterprise Linux Server release 7.8 (Maipo)
* Link to your project (optional):

Logs of error:

```bash
$ kubectl -n kube-system logs kube-flannel-ds-amd64-bc259
I0909 14:27:25.334093       1 main.go:518] Determining IP address of default interface
I0909 14:27:25.427908       1 main.go:531] Using interface with name ens192 and address IP
I0909 14:27:25.427951       1 main.go:548] Defaulting external address to interface address (IP)
W0909 14:27:25.427976       1 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0909 14:27:25.441353       1 kube.go:119] Waiting 10m0s for node controller to sync
I0909 14:27:25.441403       1 kube.go:306] Starting kube subnet manager
I0909 14:27:26.441870       1 kube.go:126] Node controller sync successful
I0909 14:27:26.441931       1 main.go:246] Created subnet manager: Kubernetes Subnet Manager - nodeName
I0909 14:27:26.441937       1 main.go:249] Installing signal handlers
I0909 14:27:26.442019       1 main.go:390] Found network config - Backend type: vxlan
I0909 14:27:26.442096       1 vxlan.go:121] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
E0909 14:27:26.442424       1 main.go:291] Error registering network: failed to acquire lease: node "node-name" pod cidr not assigned
I0909 14:27:26.443295       1 main.go:370] Stopping shutdownHandler...
```

**Comment by Oats87** [comment]
Is your `kube-controller-manager` configured to allocate node CIDR's?

**Comment by thanos1983** [comment]
> Is your `kube-controller-manager` configured to allocate node CIDR's?

I pass the variable when launching the master node but I think I have read somewhere (long time ago) that I should define the cidr in the `kube-flannel.yml` file as well. That I am not doing. I use the default file.

**Comment by dleewo** [comment]
I'm also having the same issue, but I'm on Kubernetes 1.19.3.  My `kubelet-config.yaml` has:

```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/var/lib/kubernetes/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.32.0.10"
podCIDR: "10.200.2.0/16"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
tlsCertFile: "/var/lib/kubelet/khw-worker-2.pem"
tlsPrivateKeyFile: "/var/lib/kubelet/khw-worker-2-key.pem"
```
and the kubelet is run with args:

```
/usr/local/bin/kubelet --config=/var/lib/kubelet/kubelet-config.yaml --container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --image-pull-progress-deadline=2m --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --register-node=true --v=2
```

so it is using that podCIDR, but when I run something like 

```
kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'
```

nothing is returned.

I see @thanos1983 mentioned adding the CIDR to the `kube-flannel.yml`.  Should that be done to fix this issue?

**Comment by pelamlio** [comment]
I'm also having the same issue using Kubernetes 1.19.3 and Flannel 0.13 when the podCIDR value is different from "10.244.0.0/16".

It seems to work ONLY with that value.

**Comment by kele1997** [comment]
try `kubeadm init --pod-network-cidr=10.244.0.0/16`  [reference](https://coreos.com/flannel/docs/latest/kubernetes.html)   
I recreate my cluster ,and it works.

**Comment by kele1997** [comment]
when your init cluster, you can try `kubeadm init` with `--pod-network-cidr=<cidr>` args. I tried this on my cluster , and it works.    
[reference](https://coreos.com/flannel/docs/latest/kubernetes.html)

**Comment by zahidferz** [comment]
Have you tried to  use `--pod-cidr` in the kubelet service . i think that you´re not seeing none pod cidr  with the command 
`kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'` because none of your nodes are retrieveng that pod cidr from the kubelete. So you should specify it in the /etc/systemd/system/kubelet.service. I give you and example of mine

```
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=containerd.service
Requires=containerd.service

[Service]
ExecStart=/usr/local/bin/kubelet \\
  --config=/var/lib/kubelet/kubelet-config.yaml \\
  --container-runtime=remote \\
# in case of docker unomment this 
# --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock \\
  --container-runtime-endpoint=unix:///var/run/docker/libcontainerd/docker-containerd.sock \\
  --image-pull-progress-deadline=2m \\
  --kubeconfig=/var/lib/kubelet/kubeconfig \\
  --network-plugin=cni \\
  --register-node=true \\
  --v=2 \\
  --pod-cidr="10.200.0.0/16"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

```

**Comment by EppO** [comment]
docs say that `--pod-cidr` is not required, the value should be obtained from the control plane:

> --pod-cidr string                                          The CIDR to use for pod IP addresses, only used in standalone mode.  In cluster mode, this is obtained from the master. For IPv6, the maximum number of IP's allocated is 65536 (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

**Comment by thanos1983** [comment]
Apologies to everyone that I have not tested all the proposed solutions. I will pull latest file and test tomorrow.

I am passing all the configurations through the kubeadm config file.

I will update tomorrow.

**Comment by EppO** [comment]
I've been hit by the same issue on a 1.19.4 cluster. looks like for some reasons, kube-controller-manager doesn't update the `podCIDR` of all the nodes (in my 3+3 setup, only 5 out of 6 get a podCIDR), so flannel fails to start on the nodes where it's missing: `failed to acquire lease: node "node-name" pod cidr not assigned`

my kubeadm-config configMap looks like this: 
```
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.46.128.0/21
      serviceSubnet: 192.168.1.0/24
```
and flannel's one like this:

```
apiVersion: v1
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.46.128.0/21",
      "Backend": {
        "Type": "vxlan",
        "VNI": 1,
        "Port": 8472
      }
    }
kind: ConfigMap
```

It does work on a 1.18 cluster though, with the same version of flannel, so I'm not sure it's a flannel issue

**Comment by EppO** [comment]
Strangely enough, it doesn't happen on 1.19.6, didn't see anything related in the release notes though.

**Comment by lord-bagheera** [comment]
Same behavior on fresh install on Debian 10, now I'm try changing config file

**Comment by denizetkar** [comment]
Why is this issue closed? I'm still getting the same problem in the logs of the `kube-flannel` pod:
```
E0624 01:08:38.497633       1 main.go:293] Error registering network: failed to acquire lease: node "tumwfml-statum1" pod cidr not assigned
```
I initialize my cluster with the following settings:
```bash
sudo kubeadm init --config kubeadm-config.yaml --ignore-preflight-errors NumCPU
```
where **kubeadm-config.yaml** is as follows:
```yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21.1
networking:
  podSubnet: "10.100.0.1/24"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
podCIDR: "10.100.0.1/24"
```
Then run:
```bash
mkdir -p $HOME/.kube
sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -un):$(id -gn) $HOME/.kube/config
kubectl apply -f pod-network-flannel.yml
```
where **pod-network-flannel.yml** is as follows:
```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.flannel.unprivileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
  privileged: false
  volumes:
  - configMap
  - secret
  - emptyDir
  - hostPath
  allowedHostPaths:
  - pathPrefix: "/etc/cni/net.d"
  - pathPrefix: "/etc/kube-flannel"
  - pathPrefix: "/run/flannel"
  readOnlyRootFilesystem: false
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # Privilege Escalation
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  # Capabilities
  allowedCapabilities: ['NET_ADMIN', 'NET_RAW']
  defaultAddCapabilities: []
  requiredDropCapabilities: []
  # Host namespaces
  hostPID: false
  hostIPC: false
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  # SELinux
  seLinux:
    # SELinux is unused in CaaSP
    rule: 'RunAsAny'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['psp.flannel.unprivileged']
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.100.0.1/24",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      initContainers:
      - name: install-cni
        image: quay.io/coreos/flannel:v0.14.0
        command:
        - cp
        args:
        - -f
        - /etc/kube-flannel/cni-conf.json
        - /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.14.0
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        resources:
          requests:
            # cpu: "100m"
            memory: "50Mi"
          limits:
            # cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run/flannel
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
      - name: run
        hostPath:
          path: /run/flannel
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
```

My `kubeadm version` is:
```bash
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:57:56Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
and my `kubectl version` is:
```bash
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
and finally my `kubelet --version` is:
```bash
Kubernetes v1.21.2
```
I would appreciate if someone can help me. It is okay if I have to do further troubleshooting steps.

**Comment by denizetkar** [comment]
Why is this issue closed? I'm still getting the same problem in the logs of the `kube-flannel` pod:
```
E0624 01:08:38.497633       1 main.go:293] Error registering network: failed to acquire lease: node "<node-name>" pod cidr not assigned
```
I initialize my cluster with the following settings:
```bash
sudo kubeadm init --config kubeadm-config.yaml --ignore-preflight-errors NumCPU
```
where **kubeadm-config.yaml** is as follows:
```yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21.1
networking:
  podSubnet: "10.100.0.1/24"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
podCIDR: "10.100.0.1/24"
```
Then run:
```bash
mkdir -p $HOME/.kube
sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -un):$(id -gn) $HOME/.kube/config
kubectl apply -f pod-network-flannel.yml
```
where **pod-network-flannel.yml** is as follows:
```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.flannel.unprivileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
  privileged: false
  volumes:
  - configMap
  - secret
  - emptyDir
  - hostPath
  allowedHostPaths:
  - pathPrefix: "/etc/cni/net.d"
  - pathPrefix: "/etc/kube-flannel"
  - pathPrefix: "/run/flannel"
  readOnlyRootFilesystem: false
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # Privilege Escalation
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  # Capabilities
  allowedCapabilities: ['NET_ADMIN', 'NET_RAW']
  defaultAddCapabilities: []
  requiredDropCapabilities: []
  # Host namespaces
  hostPID: false
  hostIPC: false
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  # SELinux
  seLinux:
    # SELinux is unused in CaaSP
    rule: 'RunAsAny'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['psp.flannel.unprivileged']
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.100.0.1/24",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      initContainers:
      - name: install-cni
        image: quay.io/coreos/flannel:v0.14.0
        command:
        - cp
        args:
        - -f
        - /etc/kube-flannel/cni-conf.json
        - /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.14.0
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        resources:
          requests:
            # cpu: "100m"
            memory: "50Mi"
          limits:
            # cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run/flannel
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
      - name: run
        hostPath:
          path: /run/flannel
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
```

My `kubeadm version` is:
```bash
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:57:56Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
and my `kubectl version` is:
```bash
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
and finally my `kubelet --version` is:
```bash
Kubernetes v1.21.2
```
I would appreciate if someone can help me. It is okay if I have to do further troubleshooting steps.
