### ISSUE TITLE
when the network interface bound to flannel disappears and resumes, the bridge of flannel will not be rebuilt

### ISSUE THREAD

**Issue by HirazawaUi** [flannel-io/flannel#1348]
#### Some prerequisites about issue

1. We are experimenting with a kubernetes edge node solution. The edge node is a mobile device that may be connected to any WiFi or mobile network. Therefore, the IP address of the edge node cannot be fixed. It also does not have a public IP address.
2. We use wireguard to establish a network connection between mobile devices and cloud server, because the IP address of the mobile device is not fixed, this is not a prerequisite for successfully joining kubernetes, so we use the IP address on the wireguard network interface to join kubernetes
3. Now, everything seems to be successful, but we found that when we stop wireguard and restart it (wireguard's network interface will disappear after it stops), pods in kubernetes cannot communicate over the network. Because of the disappearance of the wireguard network interface, the flannel network interface disappeared, and flannel will not rebuild it until flannel restarts next time

#### Expected Behavior

* When the edge node configuration returns to normal, the network of the kubernetes cluster is also normal

#### Current Behavior

* When the wireguard is stopped and then restored (delete the network interface and add it), the flannel.1 bridge cannot be created again until the flannel pod is restarted

#### Possible Solution

* restart flannel pod

#### My network topology

```
+-----------------------------------------------------------------------+
|                                                                       |
| +-----------+                                                         |
| |  veth01   |                                                         |
| +----+------+     Cloud Server                                        |
|      ^                Master                                         |
|      |                                                                |
|      |       +---------------------+                                  |
|      |       | cni0                |                                  |
|      +-------+ 10.50.0.1/24        |                                  |
|              +---------+-----------+                                  |
|                        ^                                              |
|                        |                                              |
|              +---------+-----------+                                  |
|              | flannel.1           |                                  |
|              | 10.50.0.0/32        |                                  |
|              +---------+-----------+                                  |
|                        ^                +-----------------------------+
|                        |                |Wireguard network interface  |
|                        |                |10.10.57.3                   +------+
|                        |                +-----------------------------+      |      +------------------------------------------------------------------+
|                        |                                              |      |      |                                                                  |
|                        |                +-----------------------------+      |      |                                                 +--------------+ |
|                        +----------------+Default network interface    |      |      |                        Edge Node                |   veth01     | |
|                                         |10.0.4.40                    |      |      |                                                 +-------+------+ |
+-----------------------------------------------------------------------+      |      |                                                         ^        |
                                                                               |      |                                                         |        |
                                                                               |      |                                +---------------------+  |        |
                                                                               |      |                                | cni0                +--+        |
                                                                               |      |                                | 10.50.1.1/24        |           |
                                                                               |      |                                +----------+----------+           |
                                                                               |      |                                           ^                      |
                                                                               |      |                                           |                      |
                                                                               |      |                                +----------+----------+           |
                                                                               |      |                                | flannel.1           |           |
                                                                               |      |                                | 10.50.1.0/32        |           |
                                                                               |      |                                +----------+----------+           |
                                                                               |      |                                           ^                      |
                                                                               |      |    +-----------------------------+        |                      |
                                                                               |      |    |Wireguard network interface  |        |                      |
                                                                               v---------->+10.10.57.2                   +--------+                      |
                                                                                      |    +-----------------------------+                               |
                                                                                      |                                                                  |
                                                                                      |    +-----------------------------+                               |
                                                                                      |    |Default network interface    |                               |
                                                                                      |    |192.168.110.100              |                               |
                                                                                      +----------------------------------+-------------------------------+

```

#### My flannel configuration

1. Cloud Server

   ```
   apiVersion: apps/v1
   kind: DaemonSet
   metadata:
     annotations:
     labels:
       app: flannel
       tier: node
     name: kube-flannel-ds-amd64
     namespace: kube-system
   spec:
     revisionHistoryLimit: 10
     selector:
       matchLabels:
         app: flannel
     template:
       metadata:
         creationTimestamp: null
         labels:
           app: flannel
           tier: node
       spec:
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: beta.kubernetes.io/os
                   operator: In
                   values:
                   - linux
                 - key: beta.kubernetes.io/arch
                   operator: In
                   values:
                   - amd64
         containers:
         - args:
           - --ip-masq
           - --kube-subnet-mgr
           command:
           - /opt/bin/flanneld
           env:
           - name: POD_NAME
             valueFrom:
               fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.name
           - name: POD_NAMESPACE
             valueFrom:
               fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
           image: quay.io/coreos/flannel:v0.11.0-amd64
           imagePullPolicy: IfNotPresent
           name: kube-flannel
           resources:
             limits:
               cpu: 100m
               memory: 50Mi
             requests:
               cpu: 100m
               memory: 50Mi
           securityContext:
             capabilities:
               add:
               - NET_ADMIN
             privileged: false
           terminationMessagePath: /dev/termination-log
           terminationMessagePolicy: File
           volumeMounts:
           - mountPath: /run/flannel
             name: run
           - mountPath: /etc/kube-flannel/
             name: flannel-cfg
         dnsPolicy: ClusterFirst
         hostNetwork: true
         initContainers:
         - args:
           - -f
           - /etc/kube-flannel/cni-conf.json
           - /etc/cni/net.d/10-flannel.conflist
           command:
           - cp
           image: quay.io/coreos/flannel:v0.11.0-amd64
           imagePullPolicy: IfNotPresent
           name: install-cni
           resources: {}
           terminationMessagePath: /dev/termination-log
           terminationMessagePolicy: File
           volumeMounts:
           - mountPath: /etc/cni/net.d
             name: cni
           - mountPath: /etc/kube-flannel/
             name: flannel-cfg
         restartPolicy: Always
         schedulerName: default-scheduler
         securityContext: {}
         serviceAccount: flannel
         serviceAccountName: flannel
         terminationGracePeriodSeconds: 30
         tolerations:
         - effect: NoSchedule
           operator: Exists
         volumes:
         - hostPath:
             path: /run/flannel
             type: ""
           name: run
         - hostPath:
             path: /etc/cni/net.d
             type: ""
           name: cni
         - configMap:
             defaultMode: 420
             name: kube-flannel-cfg
           name: flannel-cfg
     updateStrategy:
       rollingUpdate:
         maxUnavailable: 1
       type: RollingUpdate
   ```

2. Edge Node

   ```
   apiVersion: apps/v1
   kind: DaemonSet
   metadata:
     annotations:
     labels:
       app: flannel
       tier: node
     name: kube-flannel-ds-arm
     namespace: kube-system
   spec:
     revisionHistoryLimit: 10
     selector:
       matchLabels:
         app: flannel
     template:
       metadata:
         creationTimestamp: null
         labels:
           app: flannel
           tier: node
       spec:
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: beta.kubernetes.io/os
                   operator: In
                   values:
                   - linux
                 - key: beta.kubernetes.io/arch
                   operator: In
                   values:
                   - arm
         containers:
         - args:
           - --ip-masq
           - --kube-subnet-mgr
           - --iface=wg0
           command:
           - /opt/bin/flanneld
           env:
           - name: POD_NAME
             valueFrom:
               fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.name
           - name: POD_NAMESPACE
             valueFrom:
               fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
           image: quay.io/coreos/flannel:v0.11.0-arm
           imagePullPolicy: IfNotPresent
           name: kube-flannel
           resources:
             limits:
               cpu: 100m
               memory: 50Mi
             requests:
               cpu: 100m
               memory: 50Mi
           securityContext:
             capabilities:
               add:
               - NET_ADMIN
             privileged: false
           terminationMessagePath: /dev/termination-log
           terminationMessagePolicy: File
           volumeMounts:
           - mountPath: /run/flannel
             name: run
           - mountPath: /etc/kube-flannel/
             name: flannel-cfg
         dnsPolicy: ClusterFirst
         hostNetwork: true
         initContainers:
         - args
           - -f
           - /etc/kube-flannel/cni-conf.json
           - /etc/cni/net.d/10-flannel.conflist
           command:
           - cp
           image: quay.io/coreos/flannel:v0.11.0-arm
           imagePullPolicy: IfNotPresent
           name: install-cni
           resources: {}
           terminationMessagePath: /dev/termination-log
           terminationMessagePolicy: File
           volumeMounts:
           - mountPath: /etc/cni/net.d
             name: cni
           - mountPath: /etc/kube-flannel/
             name: flannel-cfg
         restartPolicy: Always
         schedulerName: default-scheduler
         securityContext: {}
         serviceAccount: flannel
         serviceAccountName: flannel
         terminationGracePeriodSeconds: 30
         tolerations:
         - effect: NoSchedule
           operator: Exists
         volumes:
         - hostPath:
             path: /run/flannel
             type: ""
           name: run
         - hostPath:
             path: /etc/cni/net.d
             type: ""
           name: cni
         - configMap:
             defaultMode: 420
             name: kube-flannel-cfg
           name: flannel-cfg
     updateStrategy:
       rollingUpdate:
         maxUnavailable: 1
       type: RollingUpdate
   ```

#### My Environment

1. Flannel version:

   * Cloud Server: 

     ```
     quay.io/coreos/flannel:v0.11.0-amd64
     ```

   * Edge Node:

     ```
     quay.io/coreos/flannel:v0.11.0-arm
     ```

2. Kubernetes version 

   ```
   kubernetes 1.16.6
   ```

3. Operating System and version:

   * Cloud Server:

     ```
     # lsb_release -a
     No LSB modules are available.
     Distributor ID:	Ubuntu
     Description:	Ubuntu 16.04.6 LTS
     Release:	16.04
     Codename:	xenial
     ```

   * Edge Node:

     ```
     lsb_release  -a
     No LSB modules are available.
     Distributor ID:	Raspbian
     Description:	Raspbian GNU/Linux 10 (buster)
     Release:	10
     Codename:	buster
     ```
