### ISSUE TITLE
iptables segfault and kube-flannel use more than 50Mi memory

### ISSUE THREAD

**Issue by tanquer** [flannel-io/flannel#1415]
The kube-flannel pod in some nodes restart very often, which exists with -1. See log below.
Checking the logs, it shows that iptables segfault, however, after using `kubectl get pod kube-flannel -o yaml` to check the last state, it shows OOMKilled. see log below.

I change the memory resources limit from default 50Mi to 100Mi, then it works well. Then I use `kubectl top` to check the memory kube-flannels use, it shows that some of them do use more than 50Mi, while some less than 50Mi. It meets expectations that those nodes, which had kube-flannel restarting very often before, use more than 50Mi memory, while those never restart nodes use less memory. see data below.

I'm wondering why there is a big differences in memory using in different nodes and if we should change the default mem limit from 50Mi to 100Mi.

## Expected Behavior

No segfault. No restart freqently.

## Current Behavior

some kube-flannel pods restart almost every hour.

logs:
```
$ kubectl -n kube-system -p logs kube-flannel-ds-gdhg8
...
E0201 17:13:29.425597       1 iptables.go:118] Failed to ensure iptables rules: Error checking rule existence: failed to check rule existence: running [/sbin/iptables -t nat -C POSTROUTING ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE --random-fully --wait]: exit status -1: 
...
```
check the last state, it shows OOMKilled:
```
$kubectl get pod kube-flannel-ds-rk9bn -n kube-system -o yaml
...
status:
  conditions:
  ...
  containerStatuses:
  - containerID: containerd://e08d37c92fca45fe6a56b395bb95182c1ead4b7307009cc22ae898439d82da4f
    image: quay.io/coreos/flannel:v0.13.1-rc2
    imageID: quay.io/coreos/flannel@sha256:cb78302df116443b4437b4a0aa4e48945728deb5982ba42de597297985ed9d19
    lastState:
      terminated:
        containerID: containerd://85765c1d5144a2ad2d8d93afc238aecbd469e2e2c8e0ea3c45b89fd8fd79c32f
        exitCode: 0
        finishedAt: "2021-03-02T09:13:57Z"
        reason: OOMKilled
        startedAt: "2021-03-02T08:35:22Z"
...
```

## Possible Solution

Change the default yaml, let the memory limit from 50Mi to 100Mi, it works well and never restarts in more than 50 hours.

Check the pod kube-flannel resources in different nodes
```
$ kubectl top pod kube-flannel-ds-8c9r7 -n kube-system
NAME                    CPU(cores)   MEMORY(bytes)
kube-flannel-ds-8c9r7   1m           56Mi
$ kubectl top pod kube-flannel-ds-gdhg8 -n kube-system
NAME                    CPU(cores)   MEMORY(bytes)
kube-flannel-ds-gdhg8   3m           54Mi
$ kubectl top pod kube-flannel-ds-t6vxr -n kube-system
NAME                    CPU(cores)   MEMORY(bytes)
kube-flannel-ds-t6vxr   2m           31Mi
```
Some kube-flannel pod do use more than 50Mi memory.

## Steps to Reproduce (for bugs)

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

## Your Environment

* Flannel version: v0.13.1-rc2
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.13-0
* Kubernetes version (if used): v1.20.4
* Operating System and version: Debian GNU/Linux 9.13 (stretch)
* Kernel: 4.19.117.bsk.4-amd64
* containerd: v1.4.3
