### ISSUE TITLE
Flanneld with --iface-regex reads only the first opt

### ISSUE THREAD

**Issue by ricoleabricot** [flannel-io/flannel#1433]
## Expected Behavior
We are using flannel like this:
```yaml
        - name: kube-flannel
          image: my-registry/flannel:v0.11.0
          command:
          - /opt/bin/flanneld
          - --ip-masq
          - --kube-subnet-mgr
          - --iface-regex=^10\.\d{1,3}\.\d{1,3}\.\d{1,3}$$
          - --iface-regex=^172\.16\.\d{1,3}\.\d{1,3}$$
          - --iface-regex=^172\.1[8-9]\.\d{1,3}\.\d{1,3}$$
          - --iface-regex=^172\.2\d\.\d{1,3}\.\d{1,3}$$
          - --iface-regex=^172\.3[0-1]\.\d{1,3}\.\d{1,3}$$
          - --iface-regex=^192\.168\.\d{1,3}\.\d{1,3}$$
``` 

We expect to accept all regex above.

## Current Behavior
Actually, we have seen that only the first regex is being used.
All IPs like 172.something or 192.something are not working as expected.

## Possible Solution
The only possible solution that we have found is to use only ONE regex, and use `OR` operators in the regex.

## Context
We are trying to use flannel in a private network context, on a kubernetes cloud provider context

## Your Environment
* Flannel version: **v0.11.0**
* Backend used (e.g. vxlan or udp): **vxlan**
* Etcd version: **etcdctl version: 3.3.13 - API version: 2**
* Kubernetes version (if used): **>= 1.17**
