### ISSUE TITLE
After installation node can not join to cluster

### ISSUE THREAD

**Issue by oguzhanoyan** [flannel-io/flannel#1451]
Hello i'm following the tutorial that showing how to install kubernetes multinode clusters on ubuntu server from here https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/ . I am installing flannel instead of calico. I can see flannel installed correctly, But i can not join to cluster from worker nodes. 
## Expected Behavior

Worker node should be joint to cluster.

## Current Behavior

if i follow the steps, firstly kubeadm init, join worker-node to cluster then installing flannel into master-node. Worker nodes status are NotReady.  But on the other hand if i follow the steps, firstly kubeadm init and then installing flannel, worker-node can not join to cluster even can not ping to master cluster. 

## Steps to Reproduce (for bugs)

1. Run master-playbook.yml
2. Run worker-playbook.yml
3. Nodes has getting error Failed to request cluster-info, will try again: Get "https://10.132.0.15:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": net/http: re
quest canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
4.

## Your Environment

* Kubernetes version (if used): 1.21.1
* Operating System and version: ubuntu

Hosts files from /etc/ansible/hosts
```
[workernodes]
X.X.X.X(PUBLIC IP) node_name=worker2 node_internal_ip=10.132.0.16
X.X.X.X(PUBLIC IP) node_name=worker3 node_internal_ip=10.132.0.19
[masternodes]
X.X.X.X(PUBLIC IP) node_name=master node_internal_ip=10.132.0.15
```

Here's my master-playbook.yml
```
---
- hosts: masternodes
  become: true
  tasks:

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Letting iptables see bridged traffic
    shell: |
      sudo modprobe br_netfilter
      lsmod | grep br_netfilter


  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  # Kubelet, kubeadm, kubec
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_internal_ip }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted


  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ node_internal_ip }}"   --node-name "{{ node_name }}" --pod-network-cidr="{{ pod_network_cidr }}"

  - name: Setup kubeconfig for "{{ user_name }}" user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/"{{ user_name }}"/.kube
     - cp -i /etc/kubernetes/admin.conf /home/"{{ user_name }}"/.kube/config
     - chown "{{ user_name }}":"{{ user_name }}" /home/"{{ user_name }}"/.kube/config

  - name: Install Flannel pod network
    become: false
    shell: kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    
  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  handlers:
    - name: docker status
      service: name=docker state=started
```

Here's my worker-playbook.yml
```
---
- hosts: workernodes
  become: true
  tasks:

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Letting iptables see bridged traffic
    shell: |
      sudo modprobe br_netfilter
      lsmod | grep br_netfilter


  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm
        - kubectl

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_internal_ip }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    shell: |
      echo " --node-name {{ node_name }}" >> /tmp/join-command.sh 
      sh /tmp/join-command.sh

  handlers:
    - name: docker status
      service: name=docker state=started
```

I am using pod_network_cidr="10.132.0.0/20 also. When i run firstly master-playbook then worker-playbook. worker-nodes stuck in join part.

Here's kubectl get pods --all-namespaces log:
```
kube-system   coredns-558bd4d5db-mlw6r                             1/1     Running   0          2m3s
kube-system   coredns-558bd4d5db-r4ptb                             1/1     Running   0          2m4s
kube-system   etcd.master-0                                        1/1     Running   0          2m18s
kube-system   kube-apiserver.master-0                              1/1     Running   0          2m18s
kube-system   kube-controller-manager.master-0                     1/1     Running   0          2m21s
kube-system   kube-flannel-ds-tvvdl                                1/1     Running   0          2m4s
kube-system   kube-proxy-pwb7h                                     1/1     Running   0          2m4s
kube-system   kube-schedulerr-0                                    1/1     Running   0          2m18s
```
