### ISSUE TITLE
k8s IPv6 dual stack: Observed a panic: Address is not an IPv4 address

### ISSUE THREAD

**Issue by bingoct** [flannel-io/flannel#1629]
i setup k8s 1.23.9 by kubeadm.

i put ipv6 CIDR before ipv4 CIDR in kubeadm-config，and config kube-apiserver advertise-ip in host ipv6.
```yaml
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    bind-address: "::"
    service-cluster-ip-range: "fd00::1234:5678:1:0/112,10.96.0.0/12"
    cluster-cidr: "fd00::1234:5678:100:0/104,10.244.0.0/16"
    node-cidr-mask-size-ipv6: "120"
    node-cidr-mask-size-ipv4: "24"
```

kubectl logs -n kube-flannel kube-flannel-ds-z9ggx  -f
E0805 05:20:57.156568       1 runtime.go:76] Observed a panic: Address is not an IPv4 address

## Expected Behavior

kube-flannel  pods run

## Current Behavior

for k8s:
kube-flannel   kube-flannel-ds-z9ggx                           ●   0/1            5 CrashLoopBackOff  

for host: flannel interface create fail
 flannel.1: <BROADCAST,MULTICAST> mtu 1414 qdisc noop state DOWN group default
    link/ether f2:57:d9:14:3d:d2 brd ff:ff:ff:ff:ff:ff

## Steps to Reproduce (for bugs)

1. flannel config
```yaml
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "SubnetLen": 24,
      "IPv6Network": "fd00::1234:5678:100:0/104",
      "IPv6SubnetLen": 120,
      "Backend": {
        "Type": "vxlan"
      }
    }
```
## Context

if i only config flannel  ipv6 single  stack, it works.
```yaml
  net-conf.json: |
    {
      "EnableIPv4": false,
      "EnableIPv6": true,
      "IPv6Network": "fd00::1234:5678:100:0/104",
      "IPv6SubnetLen": 120,
      "Backend": {
        "Type": "vxlan"
      }
    }
```
However 

## Your Environment

* Flannel version: mirrored-flannelcni-flannel:v0.19.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 
* Kubernetes version (if used): 1.23.9
* Operating System and version: Centos 7
* Link to your project (optional):
