### ISSUE TITLE
Flannel etcd client hangs on getting network config on some nodes

### ISSUE THREAD

**Issue by Capitrium** [flannel-io/flannel#1633]
Flannel pods (running as a k8s daemonset) using a dedicated etcd backend (running as a k8s statefulset) are unable to fetch the flannel network config when running on some nodes, but succeed on other nodes. On nodes where flannel's etcd client cannot get the config, other clients (i.e. etcdctl, curl) can successfully read the config, including from within the broken flannel pod.

## Expected Behavior
Flannel can get the network config from a dedicated etcd cluster from all nodes in the cluster.

## Current Behavior
Flannel fails to get the network config from a dedicated etcd cluster on many (but not all) nodes. 

## Steps to Reproduce (for bugs)
1. Deploy the provided yaml to a cluster, which creates:
  - flannel-overlays namespace
  - etcd cluster statefulset + headless service + client service + server/peer/client certificates (requires cert-manager)
  - flannel daemonset
2. Observe all pods enter Running phase, indicating all pods can connect to etcd (due to the etcdctl initContainer)
3. Check logs of all flannel pods:
  - Observe some are stuck loading from etcd:
  ```
I0818 15:27:32.208886       1 main.go:207] CLI flags config: {etcdEndpoints:https://flannel-etcd-client.flannel-overlays.svc.cluster.local:2379 etcdPrefix:/flannel.io/networks/flannel.2 etcdKeyfile:/etc/ssl/etcd/tls.key etcdCertfile:/etc/ssl/etcd/tls.crt etcdCAFile:/etc/ssl/etcd/ca.crt etcdUsername: etcdPassword: version:false kubeSubnetMgr:false kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:false ifaceCanReach: subnetFile:/run/flannel/subnet-flannel.2.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
I0818 15:27:32.209244       1 main.go:227] Created subnet manager: Etcd Local Manager with Previous Subnet: None
I0818 15:27:32.209253       1 main.go:230] Installing signal handlers
---hangs---
  ```
  - While others load the config fine:
  ```
I0818 15:27:31.488413       1 main.go:207] CLI flags config: {etcdEndpoints:https://flannel-etcd-client.flannel-overlays.svc.cluster.local:2379 etcdPrefix:/flannel.io/networks/flannel.2 etcdKeyfile:/etc/ssl/etcd/tls.key etcdCertfile:/etc/ssl/etcd/tls.crt etcdCAFile:/etc/ssl/etcd/ca.crt etcdUsername: etcdPassword: version:false kubeSubnetMgr:false kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:false ifaceCanReach: subnetFile:/run/flannel/subnet-flannel.2.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
I0818 15:27:31.489297       1 main.go:227] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.48.98.0/24
I0818 15:27:31.489317       1 main.go:230] Installing signal handlers
I0818 15:27:31.591958       1 main.go:467] Found network config - Backend type: vxlan
I0818 15:27:31.591989       1 match.go:206] Determining IP address of default interface
I0818 15:27:31.592781       1 match.go:259] Using interface with name eth0 and address 10.0.33.56
I0818 15:27:31.592809       1 match.go:281] Defaulting external address to interface address (10.0.33.56)
I0818 15:27:31.592949       1 vxlan.go:138] VXLAN config: VNI=2 Port=0 GBP=false Learning=false DirectRouting=false
I0818 15:27:31.593063       1 device.go:82] VXLAN device already exists
I0818 15:27:31.593203       1 device.go:90] Returning existing device
I0818 15:27:31.596931       1 local_manager.go:163] Found previously leased subnet (10.48.98.0/24), reusing
I0818 15:27:31.602129       1 local_manager.go:183] Allocated lease (ip: 10.48.98.0/24 ipv6: ::/0) to current node (10.0.33.56) 
I0818 15:27:31.602401       1 main.go:366] Changing default FORWARD chain policy to ACCEPT
I0818 15:27:31.602584       1 main.go:379] Wrote subnet file to /run/flannel/subnet-flannel.2.env
I0818 15:27:31.602638       1 main.go:383] Running backend.
I0818 15:27:31.602712       1 vxlan_network.go:61] watching for new subnet leases
I0818 15:27:31.687842       1 main.go:515] Waiting for 22h59m58.999798181s to renew lease
I0818 15:27:31.787180       1 main.go:515] Waiting for 22h59m58.999863886s to renew lease
I0818 15:27:31.894897       1 iptables.go:170] trying to run iptables-restore < map[filter:[[-D FORWARD -s 10.48.0.0/12 -m comment --comment flanneld forward -j ACCEPT] [-A FORWARD -s 10.48.0.0/12 -m comment --comment flanneld forward -j ACCEPT] [-D FORWARD -d 10.48.0.0/12 -m comment --comment flanneld forward -j ACCEPT] [-A FORWARD -d 10.48.0.0/12 -m comment --comment flanneld forward -j ACCEPT]]]
I0818 15:27:31.895050       1 iptables_restore.go:78] trying to run with payload *filter
-D FORWARD -s 10.48.0.0/12 -m comment --comment "flanneld forward" -j ACCEPT
-A FORWARD -s 10.48.0.0/12 -m comment --comment "flanneld forward" -j ACCEPT
-D FORWARD -d 10.48.0.0/12 -m comment --comment "flanneld forward" -j ACCEPT
-A FORWARD -d 10.48.0.0/12 -m comment --comment "flanneld forward" -j ACCEPT
COMMIT
I0818 15:27:31.911268       1 iptables.go:177] bootstrap done
…
  ```
4. `kubectl exec` into a broken flannel pod, install curl, and confirm the pod can get the config from etcd:
```
bash-5.1# apk add curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/1) Installing curl (7.79.1-r2)
Executing busybox-1.32.1-r9.trigger
OK: 21 MiB in 45 packages
bash-5.1# curl --cert /etc/ssl/etcd/tls.crt --key /etc/ssl/etcd/tls.key --cacert /etc/ssl/etcd/ca.crt https://flannel-etcd-client.flannel-overlays.svc.cluster.local:2379/v3/kv/range -XPOST -d '{"key":"L2ZsYW5uZWwuaW8vbmV0d29ya3MvZmxhbm5lbC4yL2NvbmZpZw=="}'
{"header":{"cluster_id":"7098884300614054862","member_id":"1198388253590973310","revision":"9","raft_term":"2"},"kvs":[{"key":"L2ZsYW5uZWwuaW8vbmV0d29ya3MvZmxhbm5lbC4yL2NvbmZpZw==","create_revision":"2","mod_revision":"7","version":"5","value":"eyJOZXR3b3JrIjoiMTAuNDguMC4wLzEyIiwiU3VibmV0TGVuIjoyNCwiQmFja2VuZCI6eyJUeXBlIjoidnhsYW4iLCJWTkkiOjJ9fQ=="}],"count":"1"}
```
5. `kubectl delete` the broken flannel pod while tailing the logs, and observe the last recorded error is `device or resource busy`:
```
...
I0818 15:39:13.063783       1 main.go:451] shutdownHandler sent cancel signal...
{"level":"warn","ts":"2022-08-17T14:39:13.064Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00034e8c0/flannel-etcd.flannel-overlays.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup flannel-etcd.flannel-overlays.svc.cluster.local: device or resource busy\""}
I0818 15:39:13.064772       1 main.go:463] Couldn't fetch network config: context canceled
```
6. Be as confused as I am.

## Context
I’m trying to set up additional pod subnets on K8s using [Multus](https://github.com/k8snetworkplumbingwg/multus-cni), by running an additional Flannel daemonset per-subnet that uses a dedicated etcd backend (running as a K8s statefulset) to store network configuration data separate from the main K8s etcd cluster. This would eventually be used to provide additional network interfaces via Multus to pods on dedicated subnets.

## Your Environment

* Flannel version: v0.19.1
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.3
* Kubernetes version (if used): 1.23.8
* Operating System and version: Flatcar Linux 3033.2.4

## Provided yaml
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: flannel-overlays
  name: flannel-overlays
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
  name: etcd-server
  namespace: flannel-overlays
spec:
  dnsNames:
  - localhost
  - flannel-etcd
  - '*.flannel-etcd'
  - flannel-etcd-client
  - '*.flannel-etcd-client'
  - flannel-etcd.flannel-overlays
  - '*.flannel-etcd.flannel-overlays'
  - flannel-etcd-client.flannel-overlays
  - '*.flannel-etcd-client.flannel-overlays'
  - flannel-etcd.flannel-overlays.svc
  - '*.flannel-etcd.flannel-overlays.svc'
  - flannel-etcd-client.flannel-overlays.svc
  - '*.flannel-etcd-client.flannel-overlays.svc'
  - flannel-etcd.flannel-overlays.svc.cluster.local
  - '*.flannel-etcd.flannel-overlays.svc.cluster.local'
  - flannel-etcd-client.flannel-overlays.svc.cluster.local
  - '*.flannel-etcd-client.flannel-overlays.svc.cluster.local'
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: etcd-server-tls-certs
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
  name: etcd-client
  namespace: flannel-overlays
spec:
  dnsNames:
  - localhost
  - flannel-etcd
  - '*.flannel-etcd'
  - flannel-etcd-client
  - '*.flannel-etcd-client'
  - flannel-etcd.flannel-overlays
  - '*.flannel-etcd.flannel-overlays'
  - flannel-etcd-client.flannel-overlays
  - '*.flannel-etcd-client.flannel-overlays'
  - flannel-etcd.flannel-overlays.svc
  - '*.flannel-etcd.flannel-overlays.svc'
  - flannel-etcd-client.flannel-overlays.svc
  - '*.flannel-etcd-client.flannel-overlays.svc'
  - flannel-etcd.flannel-overlays.svc.cluster.local
  - '*.flannel-etcd.flannel-overlays.svc.cluster.local'
  - flannel-etcd-client.flannel-overlays.svc.cluster.local
  - '*.flannel-etcd-client.flannel-overlays.svc.cluster.local'
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: etcd-client-tls-certs
  usages:
  - digital signature
  - key encipherment
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
  name: etcd-peer
  namespace: flannel-overlays
spec:
  dnsNames:
  - localhost
  - flannel-etcd
  - '*.flannel-etcd'
  - flannel-etcd.flannel-overlays
  - '*.flannel-etcd.flannel-overlays'
  - flannel-etcd.flannel-overlays.svc
  - '*.flannel-etcd.flannel-overlays.svc'
  - flannel-etcd.flannel-overlays.svc.cluster.local
  - '*.flannel-etcd.flannel-overlays.svc.cluster.local'
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: etcd-peer-tls-certs
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
    etcd_cluster: flannel-etcd
  name: flannel-etcd-client
  namespace: flannel-overlays
spec:
  ports:
  - name: etcd-client
    port: 2379
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
    etcd_cluster: flannel-etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
    etcd_cluster: flannel-etcd
  name: flannel-etcd
  namespace: flannel-overlays
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
  - name: peer
    port: 2380
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
    etcd_cluster: flannel-etcd
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
  name: flannel-etcd-pdb
  namespace: flannel-overlays
spec:
  minAvailable: 51%
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
      app.kubernetes.io/part-of: flannel-overlays
      etcd_cluster: flannel-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: flannel-overlays
    etcd_cluster: flannel-etcd
  name: flannel-etcd
  namespace: flannel-overlays
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
      app.kubernetes.io/part-of: flannel-overlays
      etcd_cluster: flannel-etcd
  serviceName: flannel-etcd
  template:
    metadata:
      labels:
        app: etcd
        app.kubernetes.io/name: etcd
        app.kubernetes.io/part-of: flannel-overlays
        etcd_cluster: flannel-etcd
        plane: control
      name: flannel-etcd
    spec:
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          HOSTNAME=$(hostname)

          eps() {
            EPS=""
            for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
              EPS="${EPS}${EPS:+,}https://${CLUSTER_NAME}-${i}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2379"
            done
            echo ${EPS}
          }

          member_hash() {
            etcdctl \
                --cert=/etc/etcdtls/client/etcd-tls/tls.crt \
                --key=/etc/etcdtls/client/etcd-tls/tls.key \
                --cacert=/etc/etcdtls/client/etcd-tls/ca.crt \
                --endpoints=$(eps) \
                member list | grep https://${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2380 | cut -d',' -f1
          }

          num_existing() {
            etcdctl \
                --cert=/etc/etcdtls/client/etcd-tls/tls.crt \
                --key=/etc/etcdtls/client/etcd-tls/tls.key \
                --cacert=/etc/etcdtls/client/etcd-tls/ca.crt \
                --endpoints=$(eps) \
                member list | wc -l
          }

          initial_peers() {
            PEERS=""
            for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
              PEERS="${PEERS}${PEERS:+,}${CLUSTER_NAME}-${i}=https://${CLUSTER_NAME}-${i}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2380"
            done
            echo ${PEERS}
          }

          MEMBER_HASH=$(member_hash)
          EXISTING=$(num_existing)

          # Re-joining after failure?
          if [ -n "${MEMBER_HASH}" ]; then
            echo "Re-joining member ${HOSTNAME}"

            etcdctl \
                --cert=/etc/etcdtls/client/etcd-tls/tls.crt \
                --key=/etc/etcdtls/client/etcd-tls/tls.key \
                --cacert=/etc/etcdtls/client/etcd-tls/ca.crt \
                --endpoints=$(eps) \
                member remove ${MEMBER_HASH}

            rm -rf /var/run/etcd/*
            mkdir -p /var/run/etcd/
          fi

          if [ ${EXISTING} -gt 0 ]; then
            while true; do
              echo "Waiting for ${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE} to come up"
              ping -W 1 -c 1 ${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE} > /dev/null && break
              sleep 1s
            done

            etcdctl \
                --cert=/etc/etcdtls/client/etcd-tls/tls.crt \
                --key=/etc/etcdtls/client/etcd-tls/tls.key \
                --cacert=/etc/etcdtls/client/etcd-tls/ca.crt \
                --endpoints=$(eps) \
                member add ${HOSTNAME} --peer-urls=https://${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2380 | grep "^ETCD_" > /var/run/etcd/new_member_envs

            if [ $? -ne 0 ]; then
              echo "Member add ${HOSTNAME} error"
              rm -f /var/run/etcd/new_member_envs
              exit 1
            fi

            cat /var/run/etcd/new_member_envs
            . /var/run/etcd/new_member_envs

            exec etcd --name ${HOSTNAME} \
                --initial-advertise-peer-urls https://${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2380 \
                --listen-peer-urls https://0.0.0.0:2380 \
                --listen-client-urls https://0.0.0.0:2379 \
                --advertise-client-urls https://${HOSTNAME}.${CLUSTER_NAME}-client.${POD_NAMESPACE}.svc.cluster.local:2379 \
                --data-dir /var/run/etcd/default.etcd \
                --initial-cluster ${ETCD_INITIAL_CLUSTER} \
                --initial-cluster-state ${ETCD_INITIAL_CLUSTER_STATE} \
                --peer-client-cert-auth=true \
                --peer-trusted-ca-file=/etc/etcdtls/member/peer-tls/ca.crt \
                --peer-cert-file=/etc/etcdtls/member/peer-tls/tls.crt \
                --peer-key-file=/etc/etcdtls/member/peer-tls/tls.key \
                --client-cert-auth=true \
                --trusted-ca-file=/etc/etcdtls/member/server-tls/ca.crt \
                --cert-file=/etc/etcdtls/member/server-tls/tls.crt \
                --key-file=/etc/etcdtls/member/server-tls/tls.key
                --max-request-bytes 2000000 \
                --max-wals 1 \
                --max-snapshots 1 \
                --quota-backend-bytes 8589934592 \
                --snapshot-count 5000
          fi

          for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
            while true; do
              echo "Waiting for ${CLUSTER_NAME}-${i}.${CLUSTER_NAME}.${POD_NAMESPACE} to come up"
              ping -W 1 -c 1 ${CLUSTER_NAME}-${i}.${CLUSTER_NAME}.${POD_NAMESPACE} > /dev/null && break
              sleep 1s
            done
          done

          echo "Joining member ${HOSTNAME}"
          exec etcd --name ${HOSTNAME} \
              --initial-advertise-peer-urls https://${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2380 \
              --listen-peer-urls https://0.0.0.0:2380 \
              --listen-client-urls https://0.0.0.0:2379 \
              --advertise-client-urls https://${HOSTNAME}.${CLUSTER_NAME}-client.${POD_NAMESPACE}.svc.cluster.local:2379 \
              --initial-cluster-token flannel-etcd-cluster-1 \
              --data-dir /var/run/etcd/default.etcd \
              --initial-cluster $(initial_peers) \
              --initial-cluster-state new \
              --peer-client-cert-auth=true \
              --peer-trusted-ca-file=/etc/etcdtls/member/peer-tls/ca.crt \
              --peer-cert-file=/etc/etcdtls/member/peer-tls/tls.crt \
              --peer-key-file=/etc/etcdtls/member/peer-tls/tls.key \
              --client-cert-auth=true \
              --trusted-ca-file=/etc/etcdtls/member/server-tls/ca.crt \
              --cert-file=/etc/etcdtls/member/server-tls/tls.crt \
              --key-file=/etc/etcdtls/member/server-tls/tls.key
              --max-request-bytes 2000000 \
              --max-wals 1 \
              --max-snapshots 1 \
              --quota-backend-bytes 8589934592 \
              --snapshot-count 5000
        env:
        - name: INITIAL_CLUSTER_SIZE
          value: "3"
        - name: CLUSTER_NAME
          value: flannel-etcd
        - name: ETCDCTL_API
          value: "3"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "5"
        - name: ETCD_AUTO_COMPACTION_MODE
          value: revision
        image: quay.io/coreos/etcd:v3.4.3
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                HOSTNAME=$(hostname)

                member_hash() {
                  etcdctl \
                      --cert=/etc/etcdtls/client/etcd-tls/tls.crt \
                      --key=/etc/etcdtls/client/etcd-tls/tls.key \
                      --cacert=/etc/etcdtls/client/etcd-tls/ca.crt \
                      --endpoints=$(eps) \
                      member list | grep https://${HOSTNAME}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2380 | cut -d',' -f1
                }

                eps() {
                  EPS=""
                  for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
                    EPS="${EPS}${EPS:+,}https://${CLUSTER_NAME}-${i}.${CLUSTER_NAME}.${POD_NAMESPACE}.svc.cluster.local:2379"
                  done
                  echo ${EPS}
                }

                MEMBER_HASH=$(member_hash)

                # Removing member from cluster
                if [ -n "${MEMBER_HASH}" ]; then
                  echo "Removing ${HOSTNAME} from etcd cluster"
                  etcdctl \
                      --cert=/etc/etcdtls/client/etcd-tls/tls.crt \
                      --key=/etc/etcdtls/client/etcd-tls/tls.key \
                      --cacert=/etc/etcdtls/client/etcd-tls/ca.crt \
                      --endpoints=$(eps) \
                      member remove $(member_hash)
                  if [ $? -eq 0 ]; then
                    # Remove everything otherwise the cluster will no longer scale-up
                    rm -rf /var/run/etcd/*
                  fi
                fi
        name: etcd
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: server
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - etcdctl --endpoints=https://localhost:2379 --cert=/etc/etcdtls/client/etcd-tls/tls.crt
              --key=/etc/etcdtls/client/etcd-tls/tls.key --cacert=/etc/etcdtls/client/etcd-tls/ca.crt
              endpoint status
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/run/etcd
          name: etcd-data
        - mountPath: /etc/etcdtls/member/peer-tls
          name: member-peer-tls
        - mountPath: /etc/etcdtls/member/server-tls
          name: member-server-tls
        - mountPath: /etc/etcdtls/client/etcd-tls
          name: etcd-client-tls
      volumes:
      - name: member-peer-tls
        secret:
          secretName: etcd-peer-tls-certs
      - name: member-server-tls
        secret:
          secretName: etcd-server-tls-certs
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls-certs
      - emptyDir: {}
        name: etcd-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: flannel
    app.kubernetes.io/part-of: flannel-overlays
  name: flannel
  namespace: flannel-overlays
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: flannel
    app.kubernetes.io/part-of: flannel-overlays
  name: flannel-extra-overlays
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: flannel-overlays
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: flannel.2
    app.kubernetes.io/name: flannel
    app.kubernetes.io/part-of: flannel-overlays
  name: flannel.2
  namespace: flannel-overlays
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: flannel.2
      app.kubernetes.io/name: flannel
      app.kubernetes.io/part-of: flannel-overlays
  template:
    metadata:
      annotations:
        test: t2
      labels:
        app.kubernetes.io/instance: flannel.2
        app.kubernetes.io/name: flannel
        app.kubernetes.io/part-of: flannel-overlays
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - --ip-masq
        - --etcd-endpoints=https://flannel-etcd-client.flannel-overlays.svc.cluster.local:2379
        - --etcd-prefix=/flannel.io/networks/$(NETWORK_NAME)
        - --etcd-keyfile=/etc/ssl/etcd/tls.key
        - --etcd-certfile=/etc/ssl/etcd/tls.crt
        - --etcd-cafile=/etc/ssl/etcd/ca.crt
        - --subnet-file=/run/flannel/subnet-$(NETWORK_NAME).env
        - --v=10
        command:
        - /opt/bin/flanneld
        env:
        - name: NETWORK_NAME
          value: flannel.2
        - name: ETCD_CLIENT_DEBUG
          value: "1"
        image: flannelcni/flannel:v0.19.1
        imagePullPolicy: IfNotPresent
        name: flannel
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/flannel
          name: run
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /etc/ssl/etcd/
          name: etcd-client-certs
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
      - args:
        - -c
        - |
          etcdctl \
          --endpoints="https://flannel-etcd-client.flannel-etcd.flannel-overlays.svc.cluster.local:2379" \
          --cacert="/etc/ssl/etcd/ca.crt" \
          --cert="/etc/ssl/etcd/tls.crt" \
          --key="/etc/ssl/etcd/tls.key" \
          put \
          /flannel.io/networks/flannel.2/config \
          '{"Network":"10.48.0.0/12","SubnetLen":24,"Backend":{"Type":"vxlan","VNI":2}}'
        command:
        - /bin/sh
        image: quay.io/coreos/etcd:v3.5.4
        imagePullPolicy: IfNotPresent
        name: configure-cni
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/etcd/
          name: etcd-client-certs
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: flannel
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /run/flannel
        name: run
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - name: etcd-client-certs
        secret:
          secretName: etcd-client-tls-certs
  updateStrategy:
    type: RollingUpdate
```
