### ISSUE TITLE
Pod can't access clusterip service for another pod with endpoint on the same node

### ISSUE THREAD

**Issue by oe-hbk** [flannel-io/flannel#1702]
With latest flannel 0.20.2 using vxlan (with and without DirectRouting enabled) and firewalld disabled on identical nodes with latest CentOS 7.
When node1 is running pod1 and pod2, and there is a clusterip service around pod2, pod1 cannot route traffic to the clusterip, but it can route to the pod2 ip.

If pod2 moves to node2,  and pod1 remains on node1, pod1 is now able to route traffic to both pod2 ip and the clusterip.

## Expected Behavior
Expect traffic flow from pod to clusterip when clusterip's endpoint hits a pod on the same node as original pod.

## Current Behavior
Traffic from pod1 does not properly flow to pod2 when pod2 is an endpoint for a clusterip service and pod1 tries to communicate to this clusterip.  This is only broken if pod1 and pod2 are on the same node.   Pod1 is able to contact pod2 directly by pod2's IP.

## Steps to Reproduce (for bugs)

1. Install 3 node kubeadm cluster   ( serviceSubnet: 10.233.0.0/18 , podSubnet: 10.233.64.0/18)
2. Install flannel 0.20.2 via manifest ("Network": "10.233.64.0/18", Type,vxlan, VNI: 1, Port, 8472, DirectRouting  true/or/false/doesn't matter)
3. Create nginx pod on node1, create service around this pod.  Get IP of pod and service
4. Create busybox pod (named samenode-pod) on node1, with command: ["sleep", "3600"]
5. Create busybox pod (named othernode-pod) on node2, with command: ["sleep", "3600"]
6. kubectl exec -it othernode-pod -- wget -O - pod_ip_of_nginx   <this will work>
7. kubectl exec -it othernode-pod -- wget -O - service_ip_of_nginx < this will work>
8. kubectl exec -it samenode-pod -- wget -O - pod_ip_of_nginx < this will work>
9. kubectl exec -it samenode-pod -- wget -O - service_ip_of_nginx < this will NOT work>

## Your Environment
* Flannel version: 0.20.2
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.5.5-0
* Kubernetes version (if used):  1.24.8
* Operating System and version: CentOS 7.9 (kernel 3.10.0-1160.80.1.el7.x86_64)
* Link to your project (optional):

**Comment by oe-hbk** [comment]
To reproduce, after creating a 3 node kubeadm cluster (1.24.8 in case that matters), with flannel 0.20.2

$ cat bugtest.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: bugtest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: bugtest
  labels:
    app: nginx-pod
spec:
  nodeName: node1
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: samenode-pod
  namespace: bugtest
  labels:
    app: samenode-pod
spec:
  nodeName: node1
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: othernode-pod
  namespace: bugtest
  labels:
    app: othernode-pod
spec:
  nodeName: node2
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bugtest
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-pod
  sessionAffinity: None
  type: ClusterIP
```

```
$ kubectl apply -f bugtest.yaml
namespace/bugtest created 
pod/nginx-pod created
pod/samenode-pod created
pod/othernode-pod created
service/nginx-service created
```

```
kubectl get pods,services,endpoints -n bugtest -o wide --show-labels
NAME                READY   STATUS    RESTARTS   AGE   IP              NODE    NOMINATED NODE   READINESS GATES   LABELS
pod/nginx-pod       1/1     Running   0          16m   10.233.64.103   node1    <none>           <none>            app=nginx-pod
pod/othernode-pod   1/1     Running   0          15m   10.233.65.42    node2    <none>           <none>            app=othernode-pod
pod/samenode-pod    1/1     Running   0          15m   10.233.64.104   node1    <none>           <none>            app=samenode-pod

NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE   SELECTOR        LABELS
service/nginx-service   ClusterIP   10.233.63.155   <none>        80/TCP    15m   app=nginx-pod   <none>

NAME                      ENDPOINTS          AGE   LABELS
endpoints/nginx-service   10.233.64.103:80   15m   <none>
```

This works (node2 pod to podip)
```
$ kubectl exec -it -n bugtest othernode-pod -- wget -O - 10.233.64.103
Connecting to 10.233.64.103 (10.233.64.103:80)
writing to stdout
<!DOCTYPE html>
<html>
```

This works (node2 pod to clusterip)
```
$ kubectl exec -it -n bugtest othernode-pod -- wget -O - 10.233.63.155
Connecting to 10.233.63.155 (10.233.63.155:80)
writing to stdout
<!DOCTYPE html>
<html>

```


This works (node1 to podip)
```
$ kubectl exec -it -n bugtest samenode-pod -- wget -O - 10.233.64.103
Connecting to 10.233.64.103 (10.233.64.103:80)
writing to stdout
<!DOCTYPE html>
<html>
```

But this does not (node1 to clusterip).  It just hangs.
```
$ kubectl exec -it -n bugtest samenode-pod -- wget -O - 10.233.63.155
Connecting to 10.233.63.155 (10.233.63.155:80)
```
