### ISSUE TITLE
Import/build via kustomize is broken due to missing component directory

### ISSUE THREAD

**Issue by maxmoehl** [flannel-io/flannel#1731]
The `/component` directory is missing which makes the kustomization manifest at `/Documentation/kustomization/kube-flannel` useless. I'm not entirely sure why the component directory would be needed anyways since it only sets the image tag which is also set in the `kube-flannel.yml` manifest.

## Expected Behavior
```
$ cd Documentation/kustomization/kube-flannel/
$ kustomize build
# flannel kubernetes manifest
```

## Current Behavior
```
$ cd Documentation/kustomization/kube-flannel/
$ kustomize build
Error: accumulating components: loader.New "evalsymlink failure on '/Users/username/personal/flannel/component' : lstat /Users/username/personal/flannel/component: no such file or directory"
```

## Possible Solution
I can see that there is logic in the Makefile to build a component directory via `make release-chart` but the resulting `component` directory is currently not included in the tagged commit.

Either:
- include the `/component` directory or
- drop the `component` section in `kustomization.yml` ~~(since it seems to have no effect either way).~~ it is used to create the up to date release manifest

## Steps to Reproduce (for bugs)
1. see Current Behavior

## Context
I'm currently importing the flannel manifest via the raw github URL and have to maintain the version manually. If I could use an import like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# current solution:
- https://raw.githubusercontent.com/flannel-io/flannel/v0.21.2/Documentation/kube-flannel.yml
# desired solution:
- https://github.com/flannel-io/flannel//Documentation/kustomization/kube-flannel?version=v0.21.2
```

auto-bumpers like [renovate](https://docs.renovatebot.com/modules/manager/kustomize/) would be able to manage the version for me.

From what I can tell it has been like this since it's been introduced with 3b242e9e7d72ff444c8d56566e3f2e75eb64d1e8 by @rbrtbnfgl

## Your Environment
* Flannel version: v0.21.x
* Backend used (e.g. vxlan or udp): -
* Etcd version: -
* Kubernetes version (if used): -
* Operating System and version: -
* Link to your project (optional): -

**Comment by rbrtbnfgl** [comment]
The directory is created during the make https://github.com/flannel-io/flannel/blob/master/Makefile#L171 
The kustomization is done during the release to have an updated chart between the uploaded files. With the latest version the version is updated during release and you can access it from here https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

**Comment by maxmoehl** [comment]
I'm aware of that but I would like to reference a kustomization directory instead of a single remote file.

During my first look I missed that the image tags in `/Documentation/kustomization/kube-flannel/kube-flannel.yml` are not up-to-date and this is what the `/component/kustomization.yml` is needed for. Couldn't you check-in that file so that it can be used as a remote target? It shouldn't affect the workflow from what I can tell except that you need to bump this version together with all the other references.

**Comment by rbrtbnfgl** [comment]
I am not following you. The issue is related to the `kustomization.yml` file or the manifest?

**Comment by maxmoehl** [comment]
The `kustomization.yml`. If I try to reference it from my own project like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - resource A
# - resource B
- https://github.com/flannel-io/flannel//Documentation/kustomization/kube-flannel?version=v0.21.2
```
it breaks because the component directory is not included in git. Which leads to this error:
```
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/flannel-io/flannel//Documentation/kustomization/kube-flannel?version=v0.21.2': URL is a git repository': recursed accumulation of path '/private/var/folders/nl/1gsmc4_d2csdc5wxgs84l7mh0000gn/T/kustomize-3416370955/Documentation/kustomization/kube-flannel': accumulating components: loader.New "evalsymlink failure on '/private/var/folders/nl/1gsmc4_d2csdc5wxgs84l7mh0000gn/T/kustomize-3416370955/component' : lstat /private/var/folders/nl/1gsmc4_d2csdc5wxgs84l7mh0000gn/T/kustomize-3416370955/component: no such file or directory"

```

**Comment by rbrtbnfgl** [comment]
I edited the previous comment. Don't use https://raw.githubusercontent.com/flannel-io/flannel/v0.21.2/Documentation/kube-flannel.yml but use https://github.com/flannel-io/flannel/releases/v0.21.2/download/kube-flannel.yml
It will be always updated with the right version.

**Comment by maxmoehl** [comment]
Fair, but this would still not allow me to use an auto-bumper like the syntax above. To kustomize (or renovate for that matter) it could just be any URL and doesn't allow the the features a remote target in the form of a git repository provides (like the canonical `?version=x.y.z`)

It also feels a bit weird that a kustomization file is included that can't be used as-is even though remote targets are a supported feature of kustomize.

**Comment by rbrtbnfgl** [comment]
I learnt how to use it to address the issue to update the manifest with the release. I wasn't even aware of the possibility to use `?version=x.y.z` it's good to know for future improvements.

**Comment by maxmoehl** [comment]
I still think we can drop the `component` step (including the `kustomize build` step) because apparently the version is bumped manually every time a new release is created (see e.g. a1f5a170e02c9e4200829b5069f35b61bbea4da0). If we use the `images` directive we could to so directly in `Documentation/kustomization/kube-flannel/kustomization.yml` and it would reduce the two occurrences in the manifest to one in the kustomization file like this:
```yml
# /Documentation/kustomization/kube-flannel/kube-flannel.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: flannel

resources:
- kube-flannel.yml

images:
- name: docker.io/flannel/flannel
  newTag: v0.21.2
```

We could also keep the `/component` directory and check it in. This would allow `make` to just override the file each time a version is created (but you could use `sed` to modify the main `kustomization.yml` as part of the release like this `sed -i 's/^  newTag: .*$/  newTag: $(TAG)/' Documentation/kustomization/kube-flannel/kube-flannel.yml` to avoid the extra dir and file).

WDYT?
