### ISSUE TITLE
Issue with Windows node

### ISSUE THREAD

**Issue by Khaos66** [flannel-io/flannel#1944]
## Expected Behavior
Windows pods are able to use cluster DNS to get clusterIPs and connect to them

## Current Behavior
Neighter cluster DNS nor clusterIP is accessable in pods running on Windows

## Possible Solution
This surely is just a configuration issue. Please help me find it.

## Steps to Reproduce (for bugs)
To setup the k8s cluster is q bit complex. But I deploy flannel via Ansible.
### vars.yml
```yaml
flannel_url: https://github.com/flannel-io/flannel/releases/download/v0.25.1/kube-flannel.yml
flannel_vni: 4096
flannel_port: 4789

flannel_win_url: https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/flannel/flanneld/flannel-overlay.yml
flannel_win_image: khaos66/flannel:v0.25.1-hostprocess
k8s_host_ip: 192.168.79.39
k8s_host_port: 6443
```
### deploy_flannel.yml
```yaml
- name: Bridged IPv4 traffic to iptables chains
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Download Flannel
  get_url:
    url: "{{flannel_url}}"
    dest: "/var/tmp/flannel.yml"

- name: Configure VNI and Port
  replace:
    path: /var/tmp/flannel.yml
    regexp: "\"Type\":\\W*\"vxlan\""
    replace: "\"Type\": \"vxlan\",\n        \"VNI\": {{flannel_vni}},\n        \"Port\": {{flannel_port}}"

- name: Deploy Flannel
  become: true
  become_user: kube
  kubernetes.core.k8s:
    src: /var/tmp/flannel.yml
    state: present
    wait: true

- name: Download Windows flannel
  get_url:
    url: "{{flannel_win_url}}"
    dest: "/var/tmp/win-flannel.yml"

- name: Configure Windows flannel image
  replace:
    path: /var/tmp/win-flannel.yml
    regexp: "sigwindowstools\/flannel:FLANNEL_VERSION-hostprocess"
    replace: "{{flannel_win_image}}"

- name: Configure Windows flannel host
  replace:
    path: /var/tmp/win-flannel.yml
    regexp: "KUBERNETES_SERVICE_HOST_VALUE"
    replace: "{{k8s_host_ip}}"

- name: Configure Windows flannel image
  replace:
    path: /var/tmp/win-flannel.yml
    regexp: "KUBERNETES_SERVICE_PORT_VALUE"
    replace: "{{k8s_host_port}}"

- name: Deploy Windows flannel
  become: true
  become_user: kube
  kubernetes.core.k8s:
    src: /var/tmp/win-flannel.yml
    state: present
    wait: false
```

## Context
I'm running a mixed (linux & windows) cluster on baremetal to run our CI/CD (Jenkins) on it. 
Sadly the windows pods can't access the controller pod via cluster DNS throwing error `java.net.UnknownHostException: jenkins-1713192592.jenkins-20240415t144952.svc.cluster.local`
I've also tried to use clusterIP `10.107.163.127` but even that isn't working.

## Your Environment

* Flannel version: 0.25.1
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.5.10
* Kubernetes version (if used): v1.29.2
* Operating System and version: Ubuntu 22.04.4 LTS (Control Plane) & Windows Server 2022 Standard (Node)
* Link to your project (optional):

Please let me know which logs you need and how to aquire them.
