### ISSUE TITLE
VXLAN routing rules have incorrect src ip

### ISSUE THREAD

**Issue by camflan** [flannel-io/flannel#895]
## Expected Behavior
Configuring Flannel as,

ConfigMap
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
```

and

DaemonSet
```yaml
...
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.9.0-amd64
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface=wg0" ]
        securityContext:
          privileged: true
...
```

I would expect all pods to communicate across hosts, as well as connect to service IPs

## Current Behavior
When configuring Flannel to use VXLan, pods can't communicate across hosts. I was able to determine that the routing rule was using the src IP of my public iface, not the iface I specified for flannel to use. Configuring Flannel to use UDP instead of VXLAN, all routes are correct and pods can communicate across hosts as expected.

## Possible Solution
Not sure, the workaround currently is to use UDP.

## Steps to Reproduce (for bugs)
Use my terraform project to spin up a cluster on linode, or apply my configuration to your own cluster.
https://github.com/camflan/linode-k8s

## Context
Unable to provision a cluster with VXLAN, my understanding is that UDP is not the preferred method for performance.

## Your Environment
* Flannel version: 0.9.0
* Backend used (e.g. vxlan or udp): VXLAN
* Etcd version: 3.2+ (IIRC, it's the version that kubeadm installs)
* Kubernetes version (if used): 1.8
* Operating System and version: Ubuntu 16.04
