### ISSUE TITLE
HostPort Not Mapping

### ISSUE THREAD

**Issue by ghost** [flannel-io/flannel#931]
So I'm trying to get HostPorts working, but they just don't seem to work.  I set them up in my deployment config on the container and they don't get mapped.  I've scowered the net far and wide but there doesn't seem to be a concrete way to set things up.  I've look at the merge request that is mentioned above ( kubernetes/website#5940) and it mentions the [_portmap_ documentation](https://github.com/containernetworking/plugins/blob/master/plugins/meta/portmap/README.md), that doesn't mention how to set it up either.

In terms of configuration the closest I can find is [this fellow's comment](https://github.com/kubernetes/kubernetes/issues/31307#issuecomment-343318474) and my configuration seems to match his but even now it's not clear now to make the configuration take effect.

Does anyone know of any documentation that lays out the moving parts of setting up a host port and how to set one up, and any example configuration files/commands would be useful?

## Expected Behavior
`hostport` configurations map a hostport.

## Current Behavior
Does not open a hostport

## Steps to Reproduce (for bugs)

1. Setup a container deployment with a host port.

## My configuration
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: website
  name: websiteHostPortTest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: website
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: website
    spec:
      containers:
      - image: <path to container>
        imagePullPolicy: Always
        name: website2
        ports:
        - containerPort: 80
          protocol: TCP
          hostPort: 80
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

## Context

I'm trying to host Ingress on port 80, but my test container is failing to open a host port, so if it doesn't work then Ingress won't work.

## Your Environment

* Flannel version: latest as the writing date
* Backend used (e.g. vxlan or udp): not sure how to tell
* Etcd version:
* Kubernetes version (if used): 
```json
version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version: Ubuntu Server 16.04 AMD64
* Link to your project (optional):
