### ISSUE TITLE
Flannel POD OOMKilled

### ISSUE THREAD

**Issue by jbpin** [flannel-io/flannel#963]
Flannels pod have 600 restart on node only (not on master) due to OOMKilled. 

## Expected Behavior
No Restart

## Possible Solution
Increase memory limit

## Steps to Reproduce (for bugs)
install flannel using prodived yaml (Documentation/kube-flannel.yml)
```
resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
```

## Context
1 Master / 2 Node 

## Your Environment

* Flannel version: v0.10.0-amd64
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.1.11
* Kubernetes version (if used): 1.9.4
* Operating System and version: Ubuntu 16.04.4

What's the recommended memory limit for Flannel ?
